### ISSUE TITLE
From Buck to Boost

### ISSUE THREAD

**Issue by Blop1759** [ReservedField/evic-sdk#24] opened 2016-04-11 09:58 UTC
Hello, 

First of all, I would like to congratulate all contributors for the job already done, all the basis seems to be almost covered in order to make a fully working firmware !

I'm currently testing in with a Presa 75 (so in my local git, I've set device to W007 and shunt to 100, as in OFW), the atomizer example was working quite well with a 0.7ohm SS316L coil, but as soon as battery go weaker, it stops and reboot ?!?

In the feedback to stabilize the DC/DC, only cycles are tested but never the battery : so buck and boost are not driven according to battery : buck in my opinion should be used only if desired voltage is less or equal to battery voltage and boost only for higher voltages.

With only managing cycles, the transition beetween buck and boost can be brutal and a too high current makes a reboot (I suppose)

I've modified the Amotizer.c in order to take battery into account, and it works.

Does anyone else already have this issue ?

**Comment by ReservedField** [comment] 2016-04-11 15:28
Weak battery detection is in progress (check the TODO list in the issues). Actually I've already coded it quite some time ago, but I can never seem to find the time to test it :/
It should be better than OFW, since it also checks against the battery voltage and the predicted current draw (assuming a purposely low battery resistance to avoid false positives) before firing the atomizer.

Anyways, weak battery detection is done by checking the battery voltage against a threshold (2.8V in OFW) inside the feedback cycle.

Driving buck and boost according to battery is not a very good idea. Apart from considering them "ideal" (for example, boost will have some drop due to inductance DCR and MOSFET Rdson), high power DC/DC converters such as this one usually have big output capacitances to form an effective LC filter with the inductor. I don't know how big the output caps are, but switching frequency is pretty low (150kHz) and it will probably operate in DCM at times (i.e. big current ripple), so I'm guessing it's quite big. If you immediately go for boost, for example, you're going to have a much higher voltage charging the output cap. The inrush current is only limited by two MOSFET Rdson (since it's an H-bridge topology), the inductor DCR and the capacitor ESR. This means you'll get an hefty inrush current, which will stress the circuitry and battery and will generate a big di/dt, possibly disturbing digital circuitry and causing annoying "clicks".

By starting from the lowest buck duty cycle and working the way up, we minimize this inrush current (this is called "soft-start", if you want to read up on it). Also we prevent overshooting the output voltage. I actually interpolated a formula from scope measurements which gives me a quite accurate prediction for the right duty cycle (and whether to choose buck/boost) based on battery voltage and output voltage, but in the end decided to not use it because of the issues above. Given that at 25kHz the feedback cycle gives a really good output waveform (little ripple, no ringing on power on/off, nicely monothonic and with an acceptable slew rate) I'd say it doesn't need changes, apart from the weak battery detection (just need to test it).

BTW, since I mentioned clicking: you can hear it when firing. Not only on CFW, but also in OFW. It's not a spark (sounds like it, though), it's due to the high di/dt (fast current variation) causing an audible noise from the inductor. It was much worse in the early versions of evic-sdk...

**Comment by Blop1759** [comment] 2016-04-11 16:36
Thank's for your complete answer !

In fact, when I say "weaker battery", I mean only when the battery begins to discharge while shooting whith significant current.

I have quite stress tested the "atomizer" example (up to 75W and 20A, I hardcoded this limits in order not to do stupid things) and with a battery at 80% and a 0.7SS coil, I had exactly that "click" and ... reboot when shooting with more than 10/12W, so it drives me to a "too much current somewhere" issue in that conditions.

You didn't have any kind of issue like this ? (perhaps my SS coil is responsible of this, while trying to maintain the power as the resistance increases quite fast, the voltage must be inscreased and it forces to boost too early ?? )

With a feedback driven by battery voltage (indeed, in load), BUT whith keeping the buck at firing the atomizer as you made it and keeping your cycles for buck and boost but only switching to boost with a battery voltage less than the voltage required by the atomizer, all is fine till 75w.

I haven't taken scope measurements to see if all is that perfect, but during vaping, switching between buck/boost (I also have made litlle changes in order to see on screen what was going on) seems to be smooth (must be validated with scope ;-) ).

**Comment by ReservedField** [comment] 2016-04-11 16:56
There isn't an issue because I knew about this (it's in the TODO) and it has also been reported to me outside Github :)
I confirmed the waveforms with a scope. It's smooth. It suprises me that it works by not letting it go into boost, since you are pretty much always in boost region over 20W and the transition is smooth - i.e. going slightly into boost shouldn't be a problem. By the way, there are losses, so you method will not get good output regulation if the battery voltage is close to the output voltage.
I'm suspecting you're putting out less voltage than what you're setting, or that you aren't reading the battery correctly. Could you post some code? Just to check what you're seeing.

**Comment by Blop1759** [comment] 2016-04-11 17:27
Ok ! So I must have read the TODO more in detail.

Yes, with the volt drop of the battery, 20W is the critical power.

Here are the .... very simple modifications I have made : (including Battery.h at Atomizer.c)

```
nextState = Atomizer_curState;

if(curVolts < Atomizer_targetVolts) {
    if(Atomizer_curState == POWERON_BUCK) {
        if(Atomizer_curCmr == 479) {
            // Reached maximum for buck, switch to boost if target voltage 
    //is greater than battery voltage
            if (Atomizer_targetVolts > Battery_GetVoltage()/10) {
      nextState = POWERON_BOOST;
    }
        }
        else {
            // In buck mode, increased duty cycle = increased voltage
            Atomizer_curCmr++;
        }
    }
    else if(Atomizer_curCmr > 80) {
        // Boost duty cycle must be greater than 80
        // In boost mode, decreased duty cycle = increased voltage
        Atomizer_curCmr--;
    }
}
else {
    if(Atomizer_curState == POWERON_BOOST) {
        if(Atomizer_curCmr == 479) {
            // Reached minimum for boost, switch to buck if target voltage
    //is lower than battery voltage
    if (Atomizer_targetVolts < Battery_GetVoltage()/10) {
              nextState = POWERON_BUCK;
    }
        }
        else {
            // In boost mode, increased duty cycle = decreased voltage
            Atomizer_curCmr++;
        }
    }
    else {
        if(Atomizer_curCmr <= 10) {
            // Buck duty cycles below 10 are forced to zero
            Atomizer_curCmr = 0;
        }
        else {
            // In buck mode, decreased duty cycle = decreased voltage
            Atomizer_curCmr--;
        }
    }
}
```

I think its too much simple to work perfectly, but it's the idea and seems not to be bad.
Boost, for me, must be activated only if it can boost ? (otherwise, let do the buck ? )

**Comment by ReservedField** [comment] 2016-04-11 19:06
Let's see. `Battery_GetVoltage` calls `ADC_Read`, which calls `ADC_UpdateCache` with `isBlocking` set to true. That means it waits for the ADC conversion to finish (and it may finish after more than the conversion time, since there may be conversions with higher priority in the queue). So that call surely slows the interrupt handler down a bit, and blocking calls shouldn't be made from interrupt handlers. Slowing down the feedback loop reduces the inrush current, but it's only checked on buck/boost switch so I don't see it having much impact. There must be something else... I'll have to think about it. What is your battery voltage, and what voltage are you setting on the atomizer?

On another note:

> Boost, for me, must be activated only if it can boost ? (otherwise, let do the buck ? )

I may be misunderstanding, but it _can_ (almost) always boost. Do you mean if it should boost?
I'll give you an example. Let's say the power stage has a total equivalent resistance of 10mOhm (not unreasonable considering they need heatsinking). Let's say the atomizer is drawing 20A (i.e. a 0.2ohm @ 75W), which is a nice assumption because most 18650 batteries have max continuous currents around that value. This means the power stage is dropping 0.2V from the output. Imagine your battery voltage is 3.7V and you want to output 3.6V to the atomizer (remember we're working with 0.01-0.05V accuracy, so 0.1V is a considerable difference). Your code would lock into buck mode since 3.6 < 3.7. But because of the 0.2V drop, the maximum buck output is 3.5V. You would actually need to boost as if you wanted to output 3.8V to get 3.6V at the atomizer. So, 0.1V error, while the "I-don't-care-about-battery" strategy, at that low of a boost duty cycle, would probably get around 0.01V error. The error goes up with increasing boost duty due to the asymptotic behaviour of the transfer function, but I'm digressing...

Now, I'm not saying the values I gave above are exactly right, the drop is probably lower, but you get the point. The whole idea behind negative feedback is that you have a control parameter (in this case, the combination of buck/boost mode and duty cycle) and an output value (output voltage) that you're monitoring. The loop adjusts the control parameter to try to get the output value where it wants it to be (target voltage). If certain stability conditions are satisfied, the system will stabilize in a so-called "steady state", i.e. a state where the control parameter is stable and the output value is right. And it'll do this all by itself, that's the beauty of it.

Usually you want the relationship between output and control to be continuous. We're lucky because the buck/boost transition is smooth, so it works fine. In some cases it is not, and it is addressed by using a 4-switch PWM buck-boost mode when input and output voltages are close (digressing again). By adding a check that disallows free switching between buck and boost you're breaking the continuity.

I'm not bashing your idea :) It'd work like a charm with ideal components (hell, we wouldn't even need feedback in a ideal world!). But real components don't behave as nicely as we want them to, so better use feedback and let them decide freely where they want to operate.

I don't yet fully understand why it works (battery voltage? target voltage?), but the right way to check for weak battery is just to measure voltage under load.

**Comment by Blop1759** [comment] 2016-04-11 20:27
Ouch, you're right, I wasn't thinking about blocking the interrupt ... 

Yesterday, I was testing with an LG HG2, around 4V off load, 3.83V on load from what was saying the screen (I add some info in order to see what happen in real use condition.

Coil was 0.69/0.70 ohms, 316L (I think this could be the tricky thing)

Perfect working till 75w with my mod in the feedback, "click" and reboot with the original code ?!

You're right, I should have written "should".

You're also right for the volt drop, that's why I was checking "live" battery voltage during feedback, so under load.

I think this is why it's working quite well for me as I did (but not a right way, for sure, just a fast and easy way to test if better)

What I don't understand is why with not weak battery, just discreasing voltage battery causes the boost to require so much current with the actual source that it reboots the board ?

**Comment by Blop1759** [comment] 2016-04-11 23:25
Some good news !

You were totally right, playing with cycles seems to be sufficient enough, but when changing state, you forgot to initialise cycle to the new pwm ! As they are not initialized with minimum values but with 0, boost is set to its maximum, that causes the reboots I got.

Setting new dutty cycle fix it and it now works great without looking at battery voltage. 
I think getting battery voltage with my dirty Battery_GetVoltage() does something that let the new duty cycle be initialized, that's why it was working quite well.

Finally, I only do this : 

if(nextState != Atomizer_curState) {
        Atomizer_curState = nextState;
           // Set new duty cycle
          *\* PWM_SET_CMR(PWM0, Atomizer_curState == POWERON_BUCK ? ATOMIZER_PWMCH_BUCK : ATOMIZER_PWMCH_BOOST, Atomizer_curCmr);**
        Atomizer_ConfigureConverters(nextState == POWERON_BUCK, nextState == POWERON_BOOST);
    }

Many thanks for the help !

**Comment by ReservedField** [comment] 2016-04-12 06:25
> You're also right for the volt drop, that's why I was checking "live" battery voltage during feedback, so under load.

I'm not talking about battery drop, but power stage losses. In the example, 3.7V is already under load.

> You were totally right, playing with cycles seems to be sufficient enough, but when changing state, you forgot to initialise cycle to the new pwm !

Argh! Of course, curState should be updated before setting the CMR in order to choose the right PWM channel. You're absolutely right, good catch. I'll commit a few things today, including this fix. Thank you :)

**Comment by ReservedField** [comment] 2016-04-12 16:44
Reopening this since I fixed it (a213b4f) in a slightly different way (changed the only PWM_SET_CMR to use nextState), but it should work the same. Please test and report back to ensure it's fixed.

**Comment by Blop1759** [comment] 2016-04-12 17:32
Much more elegant than my quick fix !
I will test it this evening as soon as I'm at home.

**Comment by Blop1759** [comment] 2016-04-12 20:02
Hi again, 

Every thing is fine with buck/boost switching now !

I also tested the weak battery with a 50% charged battery, firing at 65w with the atomizer example to see what happens and got a "FIRING->WEAK->NO ATOM" very fast switching states.

So it's working fine, but perhaps a little too fast in switching from weak to a new state ? (I think the "NO ATOM" is due to my 316L coil, too hot and may be out of range at 65w ? - I've already seen this no atom it in some tests before while shooting oftenly)

**Comment by ReservedField** [comment] 2016-04-12 21:17
Weak batt error is meant to be relative to the last firing, so the CFW should see it and display a weak batt screen for a few seconds before going back to normal, or something like that. Of course as soon as you call ReadInfo after the refresh window (200ms), it's going to fire it to measure, and so the error is replaced with OK, SHORT or OPEN (very unlikely to get WEAK_BATT or OVER_TEMP).

I'm more worried about the OPEN error you're seeing. Any resistance in the 0.1 - 3.5 ohm range should return OK, and I don't see a 0.7 ohm coil shooting over 3.5 ohm. If it stays in those bounds when hot, please open a new issue so we can look into it.

I'm closing this one since the issue is confirmed to be solved.

**Closed as completed by ReservedField** 2016-04-12 21:17 UTC
