### ISSUE TITLE
SSD1306 now work correctly in example

### ISSUE THREAD

**Issue by KovAlexey** [ReservedField/evic-sdk#3] opened 2015-12-25 18:34 UTC
After the upgrade stopped working example of the display SSD1306
Shows here is an image
https://pp.vk.me/c631925/v631925073/7352/vKsmN982TcU.jpg

An older version of the source code:
https://pp.vk.me/c631926/v631926073/7b9a/gYRX2Kc078Q.jpg

H \ W: 1.0
TODO_FLASHDATA tried to change.
DISPLAY_TYPE too.
Did not help.

Sorry for my English.

**Comment by ReservedField** [comment] 2015-12-25 20:06
Confirmed, commit d684fb6 broke SSD1306 display. Working on this right now.

**Comment by ReservedField** [comment] 2015-12-25 21:06
Fixed in 16419b4. Please update your local repo and rebuild.
@Ban3 The bug was caused by `A` and `B` not being defined macros. Undefined macros are always 0, so `LCD_TYPE` was always 0 and the comparison `LCD_TYPE == A` became `0 == 0`, which forced the SSD1327 driver on SSD1306 displays. My fault for not actually testing the code but only visually inspecting the patch, I missed it too.

**Closed as completed** 2015-12-25 21:07 UTC
