### ISSUE TITLE
Cuboid compatibility?

### ISSUE THREAD

**Issue by pirogoeth** [ReservedField/evic-sdk#26] opened 2016-05-06 21:24 UTC
Is there any chance that this is also compatible with the Joyetech Cuboid?

**Comment by Ban3** [comment] 2016-05-06 22:22
See #8

**Comment by ReservedField** [comment] 2016-05-07 14:00
Binaries do run on Cuboid and display works, atomizer doesn't. We're looking for Cuboid owners willing to write the necessary drivers.

Closing this one as a duplicate of #8.

**Closed as completed by ReservedField** 2016-05-07 14:00 UTC
